"""init mysql tables

Revision ID: 4b2c91786e36
Revises: 
Create Date: 2026-05-09 11:49:50.243428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2c91786e36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_dte', sa.Integer(), nullable=False),
    sa.Column('rango_desde', sa.Integer(), nullable=False),
    sa.Column('rango_hasta', sa.Integer(), nullable=False),
    sa.Column('folio_actual', sa.Integer(), nullable=False),
    sa.Column('caf_xml', sa.Text(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dtes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_dte', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('rut_receptor', sa.String(length=12), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('xml_documento', sa.Text(), nullable=True),
    sa.Column('xml_envio', sa.Text(), nullable=True),
    sa.Column('track_id', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('glosa_sii', sa.Text(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sii_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dte_id', sa.Integer(), nullable=True),
    sa.Column('operacion', sa.String(length=50), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dte_id'], ['dtes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sii_log')
    op.drop_table('dtes')
    op.drop_table('cafs')
    # ### end Alembic commands ###
